In [27]:
import numpy as np

In [28]:
def k_means(vec, K, eps, max_iter,centroids):
    #============ Your code here ====================
    # Initialization
    def euclidean(a,b):
        dist = (a-b)**2
        dist = np.sum(dist)
        return np.sqrt(dist)
    n = vec.shape[0]
    d = vec.shape[1]
    labels = np.zeros(n).astype(int)
    count = 0
    cbefore = centroids.copy()
    cafter = centroids.copy()
    # Start update
    while (count < max_iter):
        string = "Iteration: "
        print(string+str(count))
        cbefore = centroids.copy()
        # iterate over n examples in vec
        for i in range(0,len(vec)):
            minindex = -1
            # find minimum distance between xi and centroid cj
            mindist = float('inf')
            for j in range(0,len(centroids)):
                if (euclidean(vec[i],centroids[j]) < mindist):
                    mindist = euclidean(vec[i],centroids[j])
                    minindex = j
            labels[i] = minindex
        for j in range(0,K):
            ele = np.where(labels==j)[0]
            n_ele = len(ele)
            summation = np.zeros((d,))
            for i in range(0,n_ele):
                summation+= vec[ele[i]]
            centroids[j] = 1/n_ele*summation
        cafter = centroids.copy()
        diff = 0
        for i in range(0,K):
            diff+= euclidean(cbefore[i],cafter[i])**2
        diff = 1/K*diff
        print("Labels: ")
        print(labels)
        print("Centroid: ")
        print(centroids)
        print("------------")
        if (diff == eps):
            return centroids, labels
        count+=1
    #=============== End code =====================
    return centroids, labels


In [29]:
vec = np.array([[0,0],[3,1],[1,3],[7,7],[-3,-4],[-4,-3],[-4,-4]])
centroids = np.array([[7,7],[0,0]])
eps = 0
max_iter = 10000
print(centroids)
centroids, labels = k_means(vec, 2, eps, max_iter,centroids)

[[7 7]
 [0 0]]
Iteration: 0
Labels: 
[1 1 1 0 1 1 1]
Centroid: 
[[ 7  7]
 [-1 -1]]
------------
Iteration: 1
Labels: 
[1 1 1 0 1 1 1]
Centroid: 
[[ 7  7]
 [-1 -1]]
------------
